/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PunjabPolice;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author roboGOD
 */
public class printFIR extends javax.swing.JFrame {

    /**
     * Creates new form printFIR
     */
    public printFIR() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(jButton1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIR Number");
        setResizable(false);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter FIR # :-");

        jLabel2.setText("Please Enter FIR No. To Print The Report");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel2))
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fno = jTextField1.getText();
        String code = fno.substring(0,4);
        int sno = Integer.parseInt(fno.substring(4,fno.length()).trim());
        String s;
        String rec;
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        switch(code){
            case "PPSC" :
                s = "select * from senior_citizen where serial_no = '"+sno+"'";
                rec = "senior_ctz";
                break;
            case "PPMP":
                s = "select * from missing_persons where serial_no = '"+sno+"'";
                rec = "missing_persons";
                break;
            case "PPMT":
                s= "select * from mobile_theft where serial_no = '"+sno+"'";
                rec = "mobile_theft";
                break;
            case "PPVT":
                s = "select * from vehicle_theft where serial_no = '"+sno+"'";
                rec = "vehicle_theft";
                break;
            default :
                s = "";
                rec = "";
                JOptionPane.showMessageDialog(null, "Invalid FIR No.","Error!",JOptionPane.ERROR_MESSAGE);
                break;
        }
        try{
          Class.forName("com.mysql.jdbc.Driver");  
          Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/punjabpolice","root","");
          Statement st = con.createStatement();
          ResultSet rs = st.executeQuery(s);
           switch (rec) {
                case "senior_ctz":
                    while(rs.next()){
                        PrintWriter wrt = new PrintWriter("C:\\Users\\roboGOD\\Documents\\NetBeansProjects\\PunjabPolice\\src\\PunjabPolice\\Senior Citizen.txt","UTF-8");
                        wrt.println();
                        wrt.println();
                        String name = rs.getString("name");
                        wrt.println(String.format("%20s %10s %20s \r\n", "Name", ":",name));
                        String gender = rs.getString("gender");
                        wrt.println(String.format("%20s %10s %20s \r\n", "Gender", ":",gender));
                        String dob = f.format(rs.getDate("dob"));
                        wrt.println(String.format("%20s %10s %20s \r\n", "Dob", ":",name));                        
                        String spouse = rs.getString("spouse");
                        wrt.println(String.format("%20s %10s %20s \r\n", "Spouse", ":",spouse));
                        String dor = f.format(rs.getDate("dor"));
                        wrt.println(String.format("%20s %10s %20s \r\n", "Date of Retirement", ":",dor));
                        String contact = rs.getString("contact");
                        wrt.println(String.format("%20s %10s %20s \r\n", "Contact", ":",contact));
                        wrt.close();
                         Desktop.getDesktop().print(new File("C:\\Users\\roboGOD\\Documents\\NetBeansProjects\\PunjabPolice\\src\\PunjabPolice\\Senior Citizen.txt"));
                    }       break;
                case "missing_persons":
                    while(rs.next()){
                        PrintWriter wrt = new PrintWriter("C:\\Users\\roboGOD\\Documents\\NetBeansProjects\\PunjabPolice\\src\\PunjabPolice\\Missing Persons.txt","UTF-8");
                        wrt.println();
                        wrt.println();
                        String firstname =  rs.getString("first_name");
                        String lastname = rs.getString("last_name");
                        String gender = rs.getString("gender");
                        float height;
                        height = rs.getFloat("height");
                        int weight;
                        weight = rs.getInt("weight");
                        String id_marks = rs.getString("id_marks");
                        String missing_loc = rs.getString("missing_location");
                        String religion = rs.getString("religion");
                        String district = rs.getString("district");
                        String dob = String.valueOf(rs.getDate("dob"));
                        String dom = String.valueOf(rs.getDate("missing_date"));
                        wrt.println(String.format("%20s %10s %20s \r\n", "First Name", ":",firstname));
                        wrt.println(String.format("%20s %10s %20s \r\n", "Last Name", ":",lastname));
                        wrt.println(String.format("%20s %10s %20s \r\n", "Gender", ":",gender));
                        wrt.println(String.format("%20s %10s %20s \r\n", "DoB", ":",dob));
                        wrt.println(String.format("%20s %10s %20s \r\n", "Height", ":",height));
                        wrt.println(String.format("%20s %10s %20s \r\n", "Weight", ":",weight));
                        wrt.println(String.format("%20s %10s %20s \r\n", "ID Marks", ":",id_marks));
                        wrt.println(String.format("%20s %10s %20s \r\n", "Missing Date", ":",dom));
                        wrt.println(String.format("%20s %10s %20s \r\n", "Last Seen Location", ":",missing_loc));
                        wrt.println(String.format("%20s %10s %20s \r\n", "Religion", ":",religion));
                        wrt.println(String.format("%20s %10s %20s \r\n", "District", ":",district));
                        wrt.close(); 
                         Desktop.getDesktop().print(new File("C:\\Users\\roboGOD\\Documents\\NetBeansProjects\\PunjabPolice\\src\\PunjabPolice\\Missing Persons.txt"));
                     }     break;
                case "vehicle_theft":
                    while(rs.next()){
                                PrintWriter wrt = new PrintWriter("C:\\Users\\roboGOD\\Documents\\NetBeansProjects\\PunjabPolice\\src\\PunjabPolice\\Vehicle Theft.txt","UTF-8");
                                wrt.println();
                                wrt.println();
                                String fname=rs.getString("first_name");
                                String lname=rs.getString("last_name");
                                java.util.Date dob = rs.getDate("dob");
                                String gname = rs.getString("father_husband_name");
                                String address = rs.getString("address");
                                String vehtype = rs.getString("vehicle_type");
                                String vehcomp = rs.getString("vehicle_comp");
                                String vehmodel = rs.getString("vehicle_model");
                                String vehcolor = rs.getString("vehicle_color");
                                String lcno = rs.getString("license_plate_no");
                                String vehid = rs.getString("vehicle_id_no");
                                java.util.Date dom = rs.getDate("theft_date");
                                String lostloc = rs.getString("theft_location");
                                String contact = rs.getString("contact");
                                int addlen = address.length();
                                String addr[];
                                int kk=0;
                                if(addlen > 20) {
                                    int i=0,z=0;
                                    kk=0;
                                    int pointer=0;
                                    boolean flag=false;
                                    char arc[] = new char[addlen+1];
                                    address.getChars(0, addlen, arc, 0);
                                    int temp = addlen;
                                    while(temp>20){
                                        temp = temp-15;                                    
                                        kk = kk+1;
                                    }
                                    addr = new String[kk+1];
                                    int num = 0 ;
                                    while(num<kk){
                                        z =i;
                                        i+=15;
                                        while(i<z+21&&i<addlen) {
                                            if(arc[i]==' '){
                                                addr[num] = address.substring(pointer,i);
                                                pointer = i;
                                                flag = true;
                                                break;
                                            }
                                            i++;
                                        }
                                        if(!flag){
                                            z =i;
                                            i-=10;
                                            while(i<z+15&&i<addlen) {
                                            if(arc[i]==' '){
                                                addr[num] = address.substring(pointer,i);
                                                pointer = i;
                                                flag = true;
                                                break;
                                            }
                                            i++;
                                        }
                                     }
                                     if(!flag){
                                            z =i;
                                            i-=5;
                                            addr[num] = address.substring(pointer,i);
                                            pointer = i;
                                        }
                                       
                                        num++;
                                    }
                                    addr[num] = address.substring(pointer,addlen);
                                    
                                }
                                else {
                                    addr = new String[1];
                                    addr[0] = address;
                                }
                                wrt.println(String.format("%25s %10s %20s \r\n", "First Name", ":",fname));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Last Name", ":",lname));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Father's Name", ":",gname));
                                wrt.println(String.format("%25s %10s %20s \r\n", "DoB", ":",dob));
                                for(int i=0;i<kk+1;i++) {
                                    if(i==0)
                                        wrt.println(String.format("%25s %10s %20s \r\n", "Address", ":",addr[i]));
                                    else
                                        wrt.println(String.format("%25s %10s %20s \r\n", "", "",addr[i]));
                                }
                                wrt.println(String.format("%25s %10s %20s \r\n", "Vehicle Type", ":",vehtype));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Vehicle Company", ":",vehcomp));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Vehicle Model", ":",vehmodel));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Vehicle Color", ":",vehcolor));
                                wrt.println(String.format("%25s %10s %20s \r\n", "License Plate No.", ":",lcno));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Vehicle ID", ":",vehid));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Theft / Missing Date", ":",dom));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Theft / Missing Location", ":",lostloc));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Contact", ":",contact));
                                wrt.close();
                                 Desktop.getDesktop().print(new File("C:\\Users\\roboGOD\\Documents\\NetBeansProjects\\PunjabPolice\\src\\PunjabPolice\\Vehicle Theft.txt"));
                    } break;
                case "mobile_theft":
                    while(rs.next()){
                                PrintWriter wrt = new PrintWriter("C:\\Users\\roboGOD\\Documents\\NetBeansProjects\\PunjabPolice\\src\\PunjabPolice\\Mobile Theft.txt","UTF-8");
                                wrt.println();
                                wrt.println();
                                String fname=rs.getString("first_name");
                                String lname=rs.getString("last_name");
                                java.util.Date dob = rs.getDate("dob");
                                String gname = rs.getString("father_husband_name");
                                String address = rs.getString("address");
                                String mobcomp = rs.getString("mobile_comp");
                                String mobmodel = rs.getString("mobile_model");
                                String imei = rs.getString("IMEI_no");
                                String sim = rs.getString("sim_comp");
                                String lostmob = rs.getString("mob_no");
                                java.util.Date dom = rs.getDate("theft_date");
                                String lostloc = rs.getString("theft_location");
                                String contact = rs.getString("contact");
                                
                                                                int addlen = address.length();
                                String addr[];
                                int kk=0;
                                if(addlen > 20) {
                                    int i=0,z=0;
                                    kk=0;
                                    int pointer=0;
                                    boolean flag=false;
                                    char arc[] = new char[addlen+1];
                                    address.getChars(0, addlen, arc, 0);
                                    int temp = addlen;
                                    while(temp>20){
                                        temp = temp-15;                                    
                                        kk = kk+1;
                                    }
                                    addr = new String[kk+1];
                                    int num = 0 ;
                                    while(num<kk){
                                        z =i;
                                        i+=15;
                                        while(i<z+21&&i<addlen) {
                                            if(arc[i]==' '){
                                                addr[num] = address.substring(pointer,i);
                                                pointer = i;
                                                flag = true;
                                                break;
                                            }
                                            i++;
                                        }
                                        if(!flag){
                                            z =i;
                                            i-=10;
                                            while(i<z+15&&i<addlen) {
                                            if(arc[i]==' '){
                                                addr[num] = address.substring(pointer,i);
                                                pointer = i;
                                                flag = true;
                                                break;
                                            }
                                            i++;
                                        }
                                     }
                                     if(!flag){
                                            z =i;
                                            i-=5;
                                            addr[num] = address.substring(pointer,i);
                                            pointer = i;
                                        }
                                       
                                        num++;
                                    }
                                    addr[num] = address.substring(pointer,addlen);
                                    
                                }
                                else {
                                    addr = new String[1];
                                    addr[0] = address;
                                }
                                
                                wrt.println(String.format("%25s %10s %20s \r\n", "First Name", ":",fname));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Last Name", ":",lname));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Father's Name", ":",gname));
                                wrt.println(String.format("%25s %10s %20s \r\n", "DoB", ":",dob));
                                for(int i=0;i<kk+1;i++) {
                                    if(i==0)
                                        wrt.println(String.format("%25s %10s %20s \r\n", "Address", ":",addr[i]));
                                    else
                                        wrt.println(String.format("%25s %10s %20s \r\n", "", "",addr[i]));
                                }
                                wrt.println(String.format("%25s %10s %20s \r\n", "Mobile Company", ":",mobcomp));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Mobile Model", ":",mobmodel));
                                wrt.println(String.format("%25s %10s %20s \r\n", "IMEI", ":",imei));
                                wrt.println(String.format("%25s %10s %20s \r\n", "SIM Company.", ":",sim));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Lost Mobile No.", ":",lostmob));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Theft / Missing Date", ":",dom));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Theft / Missing Location", ":",lostloc));
                                wrt.println(String.format("%25s %10s %20s \r\n", "Contact", ":",contact));
                                wrt.close();
                                 Desktop.getDesktop().print(new File("C:\\Users\\roboGOD\\Documents\\NetBeansProjects\\PunjabPolice\\src\\PunjabPolice\\Mobile Theft.txt"));
                    } break;                   
                default:
                    JOptionPane.showMessageDialog(null, "'rec' Value No Match Found :: Error!!","Error!",JOptionPane.ERROR_MESSAGE);
                    break;
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e,"Error!",JOptionPane.ERROR_MESSAGE);
        }
              
        setVisible(false);
        new HomeScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HomeScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printFIR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
